import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, cp, rm } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
async function fixture(t) {
  const dir = await mkdtemp(path.join(os.tmpdir(), 'pstack-cli-test-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  for (const name of ['scripts/source.mjs']) { const dest = path.join(dir, name); await mkdir(path.dirname(dest), { recursive: true }); await cp(path.join(repo, name), dest); }
  for (const d of ['upstream/pstack', 'patches', 'content/pstack']) await mkdir(path.join(dir, d), { recursive: true });
  await writeFile(path.join(dir, 'upstream/pstack/base.txt'), 'pinned\n');
  await writeFile(path.join(dir, 'upstream/pstack/LICENSE'), 'license\n');
  const git = (...args) => { const r = spawnSync('git', args, { cwd: dir, encoding: 'utf8' }); assert.equal(r.status, 0, r.stderr); return r.stdout.trim(); };
  git('init'); git('config', 'user.email', 'test@example.invalid'); git('config', 'user.name', 'Test'); git('add', '.'); git('commit', '-m', 'source');
  const commit = git('rev-parse', 'HEAD'); const tree = git('rev-parse', `${commit}:upstream/pstack`);
  await writeFile(path.join(dir, 'upstream.lock.json'), JSON.stringify({ repository: dir, path: 'upstream/pstack', commit, tree, version: '0.15.5' }));
  // Tool interface always selects the lock subtree path; test fixtures use the real expected path.
  const lock = { repository: dir, path: 'pstack', commit, tree: git('rev-parse', `${commit}:upstream/pstack`), version: '0.15.5' };
  // Commit a matching pstack subtree and point the lock at it.
  await mkdir(path.join(dir, 'pstack')); await cp(path.join(dir, 'upstream/pstack/base.txt'), path.join(dir, 'pstack/base.txt')); await cp(path.join(dir, 'upstream/pstack/LICENSE'), path.join(dir, 'pstack/LICENSE'));
  git('add', 'pstack'); git('commit', '-m', 'matching pinned subtree'); lock.commit = git('rev-parse', 'HEAD'); lock.tree = git('rev-parse', `${lock.commit}:pstack`);
  await writeFile(path.join(dir, 'upstream.lock.json'), JSON.stringify(lock));
  return { dir, commit: lock.commit, run: (...args) => spawnSync(process.execPath, ['scripts/source.mjs', ...args], { cwd: dir, encoding: 'utf8' }) };
}

test('generate writes adaptations; verify detects generated drift and diff reports it', async t => {
  const f = await fixture(t);
  await writeFile(path.join(f.dir, 'patches/001-adapt.patch'), 'diff --git a/base.txt b/base.txt\n--- a/base.txt\n+++ b/base.txt\n@@ -1 +1 @@\n-pinned\n+adapted\n');
  let r = f.run('generate'); assert.equal(r.status, 0, r.stderr);
  assert.equal(await readFile(path.join(f.dir, 'content/pstack/base.txt'), 'utf8'), 'adapted\n');
  assert.equal(f.run('verify').status, 0);
  r = f.run('diff'); assert.equal(r.status, 0); assert.match(r.stdout, /adapted/);
  await writeFile(path.join(f.dir, 'content/pstack/extra.txt'), 'drift');
  r = f.run('verify'); assert.notEqual(r.status, 0); assert.match(r.stderr, /drift|file set differs/i);
});

test('prepare-update leaves active files unchanged when adaptation replay fails', async t => {
  const f = await fixture(t);
  await writeFile(path.join(f.dir, 'content/pstack/active.txt'), 'active generated bytes\n');
  await writeFile(path.join(f.dir, 'patches/001-conflict.patch'), 'diff --git a/base.txt b/base.txt\n--- a/base.txt\n+++ b/base.txt\n@@ -1 +1,2 @@\n pinned\n-not-pinned\n+changed\n');
  const activePaths = ['upstream/pstack/base.txt', 'upstream.lock.json', 'content/pstack/active.txt'];
  const before = await Promise.all(activePaths.map(async p => { const full = path.join(f.dir, p); try { return await readFile(full); } catch { return null; } }));
  const r = f.run('prepare-update', f.commit); assert.notEqual(r.status, 0, `${r.stdout}\n${r.stderr}`); assert.match(r.stderr, /Patch replay failed/);
  assert.deepEqual(await Promise.all(activePaths.map(async p => { const full = path.join(f.dir, p); try { return await readFile(full); } catch { return null; } })), before);
  assert.match(await readFile(path.join(f.dir, `.work/prepare-${f.commit}/failure.txt`), 'utf8'), /Patch replay failed/);
});
